# -*- coding: utf-8 -*-
"""rpg_2d_2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Mgut03lPLISocUM6qUkWfmljn2n7KWqS
"""

import sys

# =========================
# УРОВНИ
# =========================

level_str = """
...=..=...
...L..=...
.o..|...[.
.===..].[.
""".strip("\n")

# =========================
# ГЕНЕРАЦИЯ УРОВНЯ
# =========================

raw_level = []

rows = level_str.split("\n")

for row in rows:
    row_list = []
    idx = 0
    while idx < len(row):
        ch = row[idx]
        row_list.append(ch)
        idx += 1
    raw_level.append(row_list)

level = raw_level
height = len(level)
width = len(level[0])

# =========================
# ИГРОК
# =========================

player_x = player_y = 0
inventory = {}

for y in range(height):
    for x in range(width):
        if level[y][x] == ".":
            player_x, player_y = x, y
            break
    else:
        continue
    break

# =========================
# ДЕЙСТВИЯ ВЕЩИЦ
# =========================

def heal():
    print("Вы чувствуете себя лучше.")
    input()

# =========================
# БИБЛИОТЕКА ВЕЩИЦ
# =========================

ITEM_LIBRARY = [
    {
        "name": "apple",
        "type": "food",
        "icon": "o",
        "use": heal
    }
]

# =========================
# ИНВЕНТАРЬ
# =========================

def add_item(item):
    category = item["type"]
    if category not in inventory:
        inventory[category] = []
    inventory[category].append(item)

def open_inventory():
    while True:
        show_inventory()
        print("Введите название вещицы, чтобы использовать её, или q для выхода..")
        choice = input("> ").strip().lower()

        if choice == "q":
            break

        for category, items in inventory.items():
            for item in items:
                if item["name"].lower() == choice:
                    item["use"]()
                    items.remove(item)
                    return

        print("Вешица не найдена.")

def show_inventory():
    print("\n--- INVENTORY ---")
    if not inventory:
        print("Пусто.")
        return

    for category in inventory:
        items = inventory[category]
        print(f"[{category}]")
        for item in items:
            print(f"  - {item['name']}")


# =========================
# ЛОГИКА ИГРЫ
# =========================

def can_walk(x, y):
    return 0 <= x < width and 0 <= y < height and level[y][x] == "."

def try_pickup(x, y):
    tile = level[y][x]

    if tile == ".":
        return

    for item in ITEM_LIBRARY:
        if item["icon"] == tile:
            add_item(item)
            level[y][x] = "."
            print(f"Подобрали '{item['name']}'")
            return

# =========================
# ПРОРИСОВКА ЭКРАНА
# =========================

def render():
    for y in range(height):
        row = ""
        for x in range(width):
            if x == player_x and y == player_y:
                row += "P"
            else:
                row += level[y][x]
        print(row)
    print("\nWASD движение | I инвентарь | Q выход")

# =========================
# ГЛАВНЫЙ ЦИКЛ
# =========================

while True:
    render()
    cmd = input("> ").lower().strip()

    if cmd == "q":
        sys.exit()

    if cmd == "i":
        open_inventory()
        continue

    dx = dy = 0
    if cmd == "w": dy = -1
    elif cmd == "s": dy = 1
    elif cmd == "a": dx = -1
    elif cmd == "d": dx = 1
    else:
        continue

    nx = player_x + dx
    ny = player_y + dy

    try_pickup(nx, ny)

    if can_walk(nx, ny):
        player_x, player_y = nx, ny