# -*- coding: utf-8 -*-
"""2d_rpg_levels_s1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11RxBnrCTK_zNYub9q6yrOtwAhjEZAZN8
"""

import os
import sys

# --- SETTINGS ---
strip_every_other = True


# --- LEVEL DATA (multi-line string) ---
level_str = """
...|..|...
...|..|.|.
........|.
.|||..|.|.
""".strip("\n")


# --- PARSE LEVEL AND APPLY STRIP MODE ---
raw_level = []

rows = level_str.split("\n")

for row in rows:
    row_list = []
    idx = 0
    while idx < len(row):
        ch = row[idx]
        row_list.append(ch)
        idx += 1
    raw_level.append(row_list)


if strip_every_other:
    level = []
    for row in raw_level:
        new_row = []
        i = 0
        while i < len(row):
            ch = row[i]
            if i % 2 == 1:
                new_row.append(" ")
            else:
                new_row.append(ch)
            i += 1
        level.append(new_row)
else:
    level = raw_level

height = len(level)
width = len(level[0])


# --- FIND START (first "." on map) ---
player_x = player_y = None
x = 0
y = 0
while y < height:
    while x < width:
        if level[y][x] == ".":
            player_x, player_y = x, y
            break
    if player_x is not None:
        break


def clear():
    if os.name == "nt":
        command = "cls"
    else:
        command = "clear"

    os.system(command)



def render():
    clear()
    x = 0
    y = 0
    while y < height:
        row = ""
        while x < width:
            if x == player_x and y == player_y:
                row += "P"
            else:
                row += level[y][x]
            x += 1
        y += 1
        print(row)

    print("\nUse WASD to move (stackable). q to quit.")
    print(f"Strip mode: {'ON' if strip_every_other else 'OFF'}")


def can_walk(x, y):
    if 0 <= x < width and 0 <= y < height:
        return level[y][x] == "."
    return False


# --- MAIN LOOP ---
while True:
    render()
    cmds = input("> ").strip().lower()

    if cmds == "q":
        print("Goodbye!")
        sys.exit()

    for cmd in cmds:
        dx = dy = 0
        if cmd == "w": dy = -1
        elif cmd == "s": dy = 1
        elif cmd == "a": dx = -1
        elif cmd == "d": dx = 1
        else:
            continue

        nx = player_x + dx
        ny = player_y + dy

        if 0 <= nx < width and 0 <= ny < height and level[ny][nx] == " ":
            nx2 = nx + dx
            ny2 = ny + dy
            if can_walk(nx2, ny2):
                nx, ny = nx2, ny2
            else:
                continue

        if can_walk(nx, ny):
            player_x, player_y = nx, ny