# -*- coding: utf-8 -*-
"""snake_task_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_ZG03j1HIYRllQoyr81mIaYvZpaKqinG
"""

import sys
import random

# =========================
# НАСТРОЙКИ
# =========================

WIDTH = 8
HEIGHT = 8

# =========================
# СОЗДАНИЕ УРОВНЯ
# =========================

level = []

y = 0
while y < HEIGHT:
    row = []
    x = 0
    while x < WIDTH:
        row.append(".")
        x += 1
    level.append(row)
    y += 1

# =========================
# ЗМЕЙКА (ГОЛОВА)
# =========================

snake_x = 0
snake_y = 0

# =========================
# ЯБЛОКО
# =========================

apple_x = 0
apple_y = 0

def spawn_apple():
    global apple_x, apple_y

    while True:
        x = random.randint(0, WIDTH - 1)
        y = random.randint(0, HEIGHT - 1)

        if x != snake_x or y != snake_y:
            apple_x = x
            apple_y = y
            break

spawn_apple()

# =========================
# ПРОВЕРКИ
# =========================

def out_of_bounds(x, y):
    if x < 0:
        return True
    if y < 0:
        return True
    if x >= WIDTH:
        return True
    if y >= HEIGHT:
        return True
    return False

# =========================
# ПРОРИСОВКА
# =========================

def render():
    print("\n" * 5)

    y = 0
    while y < HEIGHT:
        row = ""
        x = 0
        while x < WIDTH:
            if x == snake_x and y == snake_y:
                row += "S"  + " "
            elif x == apple_x and y == apple_y:
                row += "A"  + " "
            else:
                row += level[y][x] + " "
            x += 1
        print(row)
        y += 1

    print("\nWASD — движение | Q — выход")

# =========================
# ГЛАВНЫЙ ЦИКЛ
# =========================

while True:
    render()
    cmd = input("> ").lower().strip()

    if cmd == "q":
        sys.exit()

    # поддержка ввода типа "wwaass"
    i = 0
    while i < len(cmd):
        dx = 0
        dy = 0

        if cmd[i] == "w":
            dy = -1
        elif cmd[i] == "s":
            dy = 1
        elif cmd[i] == "a":
            dx = -1
        elif cmd[i] == "d":
            dx = 1
        else:
            i += 1
            continue

        new_x = snake_x + dx
        new_y = snake_y + dy

        # выход за границы — проигрыш
        if out_of_bounds(new_x, new_y):
            print("Игра окончена! Змейка вышла за границы.")
            sys.exit()

        snake_x = new_x
        snake_y = new_y

        # съели яблоко
        if snake_x == apple_x and snake_y == apple_y:
            print("Яблоко съедено!")
            spawn_apple()

        i += 1